//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 6? 4 2018 10:24:56
//
//      Input file      : 
//      Component name  : chongpai_ram0_i
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module Chongpai_Ram0_I(clock, data, rdaddress, rden, wraddress, wren, q);
   input         clock;
   input [35:0]  data;
   input [12:0]  rdaddress;
   input         rden;
   input [12:0]  wraddress;
   input         wren;
   output [35:0] q;
   
   
   wire [35:0]   sub_wire0;
   
   assign q = sub_wire0[35:0];
   
   
   altsyncram #("CLOCK0", "BYPASS", "BYPASS", "BYPASS", "BYPASS", "Stratix II", "altsyncram", 8192, 8192, "DUAL_PORT", "NONE", "CLOCK0", "FALSE", "CLOCK0", "DONT_CARE", 13, 13, 36, 36, 1) altsyncram_component(.address_a(wraddress), .clock0(clock), .data_a(data), .rden_b(rden), .wren_a(wren), .address_b(rdaddress), .q_b(sub_wire0));
   
endmodule
