function Hd = DDC_Lowpass64
%DDC_LOWPASS64 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 09-May-2019 18:04:07

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 40;  % Sampling Frequency

N     = 63;   % Order
Fpass = 5;    % Passband Frequency
Fstop = 6.5;  % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 1;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
