//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 5? 24 2018 10:21:22
//
//      Input file      : 
//      Component name  : fir_16_0
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module Fir_16_0(clk, reset_n, coeff_in_clk, coeff_in_areset, ast_sink_data, ast_sink_ready, ast_sink_valid, ast_sink_error, ast_source_data, ast_source_ready, ast_source_valid, ast_source_error);
   input         clk;
   input         reset_n;
   input         coeff_in_clk;
   input         coeff_in_areset;
   input [11:0]  ast_sink_data;
   output        ast_sink_ready;
   input         ast_sink_valid;
   input [1:0]   ast_sink_error;
   output [23:0] ast_source_data;
   input         ast_source_ready;
   output        ast_source_valid;
   output [1:0]  ast_source_error;
   
   
   
   Fir_16_0_0002 fir_16_0_inst(.clk(clk), .reset_n(reset_n), .coeff_in_clk(coeff_in_clk), .coeff_in_areset(coeff_in_areset), .ast_sink_data(ast_sink_data), .ast_sink_ready(ast_sink_ready), .ast_sink_valid(ast_sink_valid), .ast_sink_error(ast_sink_error), .ast_source_data(ast_source_data), .ast_source_ready(ast_source_ready), .ast_source_valid(ast_source_valid), .ast_source_error(ast_source_error));
   
endmodule
