//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 5? 20 2018 20:34:39
//
//      Input file      : 
//      Component name  : add
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module add(aclr, clock, dataa, datab, result);
   input         aclr;
   input         clock;
   input [23:0]  dataa;
   input [23:0]  datab;
   output [23:0] result;
   
   
   wire [23:0]   sub_wire0;
   
   assign result = sub_wire0[23:0];
   
   
   LPM_ADD_SUB #("ADD", "ONE_INPUT_IS_CONSTANT=NO,CIN_USED=NO", 1, "SIGNED", "LPM_ADD_SUB", 24) LPM_ADD_SUB_component(.aclr(aclr), .clock(clock), .datab(datab), .dataa(dataa), .result(sub_wire0));
   
endmodule
